### PR TITLE
Add standard style

### PR DESCRIPTION
**Pull request by ryanseys**
@ironwallaby What do you think of this? It's hooked up to tests too.

More info: https://github.com/feross/standard

### CODE REVIEW

**Comment by ironwallaby** [comment]
I think it's opinionated in the wrong direction. ;) (I favor double quotes, semicolons, and no spaces after keywords or function names.)

That said, it's your project, and I'm happy with obeying whatever style guide you prefer: any guide is better than none!

**Comment by ironwallaby** [comment]
All the changes look good!

**Comment by ryanseys** [comment]
> That said, it's your project, and I'm happy with obeying [...]

That's not how open source works :) Happy to defer this until we come up with a better alternative. I'm a big fan of semicolons too but also really like that `standard` doesn't have any configuration and *just works*.

Let's let this PR sit and stew for a bit. Maybe the style will grow on us :deciduous_tree:

**Comment by ironwallaby** [comment]
Completely agree that the zero configuration is super nice. I'll start my changes in #13 from your branch and see how it works for me. :)

**Comment by ryanseys** [comment]
:+1: Thanks for giving it a shot. (FWIW - this is the first project I'm trying standard with too)

**Comment by ironwallaby** [comment]
So, after using standard style, my only major problem with is forcing `if` branches to be squished together. I think it hurts code clarity. However, in each instance that it came up in the code, there were code stink issues anyway, so refactoring removed the problem entirety.

So, I suppose in that case, requiring weird code style patterns helped. :+1:

While I'm not sold on `standard`, it's by no means terrible, and it might be worth running with (at least in the short term!) on a small library like this.

**Pull request merged**
